services:
    postgis:
        image: postgis/postgis:16-3.4
        container_name: postgis
        environment:
            POSTGRES_DB: gis
            POSTGRES_USER: gisuser
            POSTGRES_PASSWORD: gispass
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"

    geoserver:
        image: kartoza/geoserver:2.24.2
        container_name: geoserver
        environment:
            GEOSERVER_ADMIN_USER: admin
            GEOSERVER_ADMIN_PASSWORD: geoserver
            DB_HOST: postgis
            DB_PORT: 5432
            DB_DATABASE: gis
            DB_SCHEMA: public
            DB_USER: gisuser
            DB_PASS: gispass
        volumes:
            - ./geoserver_data:/opt/geoserver/data_dir
        ports:
            - "8080:8080"
        depends_on:
            - postgis

    geoclient:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: geoclient
        restart: unless-stopped
        ports:
            - "5173:5173"
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        depends_on:
            - postgis
            - geoserver
